@startuml

title Nhập kho - Use Case Diagram

left to right direction
actor "Nhân viên" as nv
rectangle "<<subsystem>>\nInbound-Outbound" {
  ' usecase "Quét RFID" as UC1
  usecase "Kiểm tra số lượng" as UC1
  usecase "Tạo phiếu nhập kho" as UC2
  usecase "Thực hiện Nhập kho" as UC3
  usecase "Kiểm tra chất lượng" as UC5
  usecase "Tạo đơn xử lý lỗi" as UC6
  ' usecase "Chọn vị trí lưu trữ" as UC6
}

nv --> UC3
' UC3 ..> UC1: <<include>>
UC3 ..> UC2: <<include>>
' UC1 <.. UC4: <<extend>>
UC3 ..> UC1: <<include>>
UC3 ..> UC5: <<include>>
UC5 <. UC6: <<extend>>
' UC3 ..> UC6: <<include>>

@enduml