@startuml
title Quy trình nhập kho sử dụng RFID

|Nhân viên nhập kho|
start

'--- Chọn cách tạo phiếu nhập ---
:Nhấn nút "Nhập kho";

|Hệ thống|
:Hiển thị danh sách đơn nhập
(ĐVSX / Bên thứ ba / Đơn chuyển kho)
và nút "Tạo phiếu nhập kho";

|Nhân viên nhập kho|
:Chọn "Tạo phiếu nhập kho";

if ("Tạo từ đơn có sẵn\nhay tạo mới từ đầu?") then
  -> "Từ đơn có sẵn";
  :Chọn một đơn nhập kho / hoá đơn cần thực hiện;

  '--- Xử lý RFID cho sản phẩm ---
  if ("Đơn nhập từ bên thứ ba\ncó sản phẩm mới?") then
    -> YES;
    :Nhập thông tin sản phẩm mới;
    :Sinh mã RFID cho sản phẩm mới;
  else
    -> NO;
    :Sử dụng dữ liệu sản phẩm đã có;
  endif

else
  -> "Tạo phiếu mới từ đầu";
  |Hệ thống|
  :Yêu cầu chọn loại nhập kho
  (ĐVSX / Bên thứ ba / Đơn chuyển kho);
  |Nhân viên nhập kho|
  :Chọn sản phẩm và nhập số lượng dự kiến;
endif

:In / gắn thẻ RFID cho lô hàng;

:Đem lô hàng quét RFID tại kho;

'--- LOOP bắt đầu từ đây ---
repeat

  |Hệ thống|
  :Đọc thông tin từ thiết bị RFID;
  :So sánh với phiếu nhập hàng;
  |Nhân viên nhập kho|
  if ("Lô hàng không đủ số lượng?") then
    -> NO;
    :Hiển thị cảnh báo thiếu số lượng;
    :Hiển thị lựa chọn tiếp tục nhập kho;
    if ("Đồng ý nhập kho?") then
      -> YES;
      :Ghi nhận trạng thái không đủ số lượng của lô hàng\nvào phiếu nhập kho;

    else
      -> NO;
      :Bỏ qua lô hàng này;
      :Ghi nhhận trạng thái không cần kiểm tra chất lượng cho lô hàng;
    endif
    
  |Hệ thống|
  else
    -> YES;
    :Ghi nhận trạng thái đủ số lượng của lô hàng cho phiếu nhập kho;
  endif

repeat while (Còn lô hàng cần quét?) is (YES)
-> NO;


|Nhân viên nhập kho|
if ("Có muốn kiểm tra chất lượng?/Hàng cần kiểm tra chất lượng?") then
  -> YES;
  :Kiểm tra chất lượng/Phân loại hàng hoá;
  if ("Có hàng lỗi?") then
    -> YES;
    :Đánh dấu lô hàng có hàng lỗi;
  else
    -> NO;
    :Đánh dấu lô hàng đạt chất lượng;
  endif
else
  -> NO;
  :Bỏ qua kiểm tra chất lượng;
  |Hệ thống|
  :Ghi nhận trạng thái nhập kho không kiểm tra chất lượng\n của lô hàng vào phiếu nhập kho;
endif

|Nhân viên nhập kho|
if ("Đơn hàng có hàng lỗi?") then
  -> YES;
  fork
    :Chọn vị trí lưu trữ cho lô hàng lỗi;
  fork again
    :Chọn vị trí lưu trữ cho lô hàng đạt;
  end fork
else
  -> NO;
  :Chọn vị trí lưu trữ cho lô hàng đạt;
endif

:Bấm nút xác nhận nhập kho;

|Hệ thống|
:Cập nhật dữ liệu cho phiếu nhập kho (trạng thái, vị trí);

stop
@enduml

