@startuml

title Quy trình xuất kho sử dụng RFID (số lượng lớn & lẻ)

' |Bộ phận sản xuất/Giao hàng|
' start
' :Tạo yêu cầu xuất kho;
|Nhân viên xuất kho|
start
:Nhấn nút xuất kho;

|Hệ thống|
:Hiển thị danh sách yêu cầu xuất kho
(Khách hàng / Đơn vị sản xuất / Đơn chuyển kho)
và nút "Tạo phiếu xuất kho";

|Nhân viên xuất kho|
if ("Tạo từ yêu cầu có sẵn\nhay tạo mới từ đầu?") then
  -> "Từ yêu cầu có sẵn";
  :Chọn một yêu cầu xuất kho / hoá đơn cần thực hiện;
  :Tạo phiếu xuất kho dựa trên dữ liệu được yêu cầu;

else
  -> "Tạo phiếu mới từ đầu";
  :Yêu cầu chọn loại nhập kho
  (Khách hàng / Đơn vị sản xuất / Đơn chuyển kho);
  |Nhân viên xuất kho|
  :Chọn sản phẩm và nhập số lượng xuất kho dự kiến;
endif

' |Nhân viên xuất kho|
' :Tiếp nhận yêu cầu xuất kho;
' :Tạo phiếu xuất kho dựa trên dữ liệu được yêu cầu;
' :Chuẩn bị hàng theo phiếu xuất kho;

' |Hệ thống|
' :Kiểm tra loại xuất kho;

|Nhân viên xuất kho|
:Di chuyển hàng đến cổng kiếm soát RFID;

|Hệ thống|
:Đọc thông tin sản phẩm từ máy đọc RFID;
' if ("Là xuất kho số lượng lớn?") then
  
'   -> YES;
'   :Di chuyển hàng đến cổng kiểm soát RFID;
  
'   :Đọc thông tin sản phẩm từ máy đọc RFID;
' else
'   -> NO;
'   :Nhập số lượng hàng xuất lẻ;
  
'   :Gắn nhãn RFID mới cho phần còn lại;
' endif

|Hệ thống|
:So sánh, đối chiếu dữ liệu với phiếu xuất kho;

|Nhân viên xuất kho|
:Xác nhận xuất kho;

|Hệ thống|
if ("Số lượng hàng đủ?") then
  -> YES;
  :Hệ thống trừ số lượng tồn kho;
  :Ghi nhận lịch sử xuất kho (ngày giờ, người thực hiện, mã hàng, số lượng...);
  stop
else
  -> NO;
  :Hệ thống từ chối xuất kho và lưu lại trạng thái của phiếu xuất kho;
  stop
' if ("Số lượng khớp với phiếu?") then
'   -> YES;
'   :Hiển thị thông báo đủ điều kiện xuất kho;
'   :Hệ thống cho phép xuất kho;
' else
'   -> NO;
'   :Hiển thị cảnh báo về hoạt động bất thường (sai mã, sai số lượng, sai vị trí...);
'   :Hiển thị thông báo có muốn tiếp tục xuất kho;
'   if ("Đồng ý xuất kho?") then
'     -> YES;
'     : Hệ thống tạo biên bản xuất kho bất thường;
'   else
'     -> NO;
'     :Hệ thống từ chối xuất kho và tạo biên bản;
'     stop
'   endif
' endif



@enduml